alert("Bem vindo(a)! A seguir pediremos que informe alguns dados.")
let nome  = prompt("Informe o seu nome:")
let idade = prompt("Digite a sua idade:")
let confirmIdade = prompt("Confirme a sua idade")
alert(`O seu nome é ${nome} e você tem ${confirmIdade} anos.`)